### ISSUE TITLE
missing "SAVE" button

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#6]
on the webgui theres no "save" button, although I've seen that's there is the code related to.
by the way I tried to configure via CLI, I can set the parameters, but nothing works.

![seleccio_030](https://user-images.githubusercontent.com/10468371/37680344-e7a0cd56-2c83-11e8-8179-5c7528846ad2.png)

**Comment by zipurman** [comment]
Save button should be at the bottom of the settings page? If not, please send a screenshot of the entire page so I can see where the error is occurring.

**Comment by txsastre** [comment]
hi ! yes I've seen the snapshots you have deployed on the docs.

in my situation at the bottom I don't see the "save" button, tested on a firefox 58 and 59, and also with a iexplorer.

also checked the code and I see and the end of it the the code about this button.

as I cannot capture the hole screen, I've done 3 snapshots, there's no button :/

![seleccio_032](https://user-images.githubusercontent.com/10468371/37734646-1592e3b6-2d4c-11e8-8e19-d197e814f3e0.png)
![seleccio_033](https://user-images.githubusercontent.com/10468371/37734651-17dd5cfa-2d4c-11e8-933f-ca8b5e2b57c0.png)
![seleccio_034](https://user-images.githubusercontent.com/10468371/37734656-1a9fd9c2-2d4c-11e8-93ca-09bd48d27a1a.png)

**Comment by zipurman** [comment]
Looks like it is stopping at the Storage Domains. What Storage domains do you have in your oVirt setup? 

You could also run the following on the BackupVM:

tail /var/log/apache2/error.log -f 

Then refresh your browser on the settings page of the script to see what errors come up in the console.

Then just let me know.

**Comment by txsastre** [comment]
Hi !
I have 3 storage domains, 1 was created at installation time "ovirt-manage-repository" the other 2 are for VM and ISO

![seleccio_016](https://user-images.githubusercontent.com/10468371/37756819-26d8e7e2-2dab-11e8-888a-602a1273bc36.png)

**Comment by txsastre** [comment]
and the error seems related to a missing variable.

`````
[Thu Mar 22 08:41:31.432906 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 127, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433011 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 146, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433038 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 165, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433058 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 184, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433077 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 203, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433096 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 222, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433115 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 239, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433139 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 260, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433178 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 282, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433198 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 301, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433241 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 321, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433265 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 361, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433279 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined index: maxlength in /var/www/html/functions.php on line 169, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433307 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 379, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433322 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined index: maxlength in /var/www/html/functions.php on line 169, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433339 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 397, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433353 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined index: maxlength in /var/www/html/functions.php on line 169, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433370 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 415, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433383 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined index: maxlength in /var/www/html/functions.php on line 169, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433406 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 456, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.433428 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 474, referer: http://192.168.222.14/site/?area=0
[Thu Mar 22 08:41:31.494298 2018] [:error] [pid 27501] [client 192.168.222.50:47772] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/functions.php:236\nStack trace:\n#0 /var/www/html/functions.php(408): ovirt_rest_api_call('GET', 'clusters/')\n#1 /var/www/html/area/settings.php(483): sb_clusterlist()\n#2 /var/www/html/site/index.php(9): require('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/functions.php on line 236, referer: http://192.168.222.14/site/?area=0
```

**Comment by zipurman** [comment]
The config.php must be missing. New version will catch this.

**Comment by txsastre** [comment]
no, there it is. :/

ok, don't worry, I will wait to the new version :D

**Comment by txsastre** [comment]
version 0.6.0. same error

looks that there's some problem when looking the Clusters  "ovirt_rest_api_call('GET', 'clusters/')" at the end.

```
root@VMMIGRATE:~# tail /var/log/apache2/error.log -f
[Sun Mar 25 13:37:12.918999 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 15 in /var/www/html/functions.php on line 934, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919010 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 16 in /var/www/html/functions.php on line 935, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919022 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 17 in /var/www/html/functions.php on line 936, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919033 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 18 in /var/www/html/functions.php on line 937, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919044 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 19 in /var/www/html/functions.php on line 938, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919055 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 20 in /var/www/html/functions.php on line 939, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919067 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 21 in /var/www/html/functions.php on line 940, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:37:12.919078 2018] [:error] [pid 1361] [client 192.168.222.8:46494] PHP Notice:  Undefined offset: 22 in /var/www/html/functions.php on line 941, referer: https://192.168.222.200/ovirt-engine/webadmin/?locale=en_US
[Sun Mar 25 13:41:01.383237 2018] [:error] [pid 1379] [client 192.168.222.57:58591] PHP Notice:  Undefined variable: settings in /var/www/html/area/settings.php on line 49, referer: https://192.168.222.14/index.php
[Sun Mar 25 13:41:01.525137 2018] [:error] [pid 1379] [client 192.168.222.57:58591] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/functions.php:241\nStack trace:\n#0 /var/www/html/functions.php(427): ovirt_rest_api_call('GET', 'clusters/')\n#1 /var/www/html/area/settings.php(505): sb_clusterlist()\n#2 /var/www/html/site/index.php(6): require('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/functions.php on line 241, referer: https://192.168.222.14/index.php
[Sun Mar 25 13:44:33.298328 2018] [:error] [pid 1379] [client 192.168.222.57:58626] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/functions.php:241\nStack trace:\n#0 /var/www/html/functions.php(427): ovirt_rest_api_call('GET', 'clusters/')\n#1 /var/www/html/area/settings.php(505): sb_clusterlist()\n#2 /var/www/html/site/index.php(6): require('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/functions.php on line 241, referer: https://192.168.222.14/index.php?area=0
```

**Comment by zipurman** [comment]
The code is expecting to get xml from the api and it isnt. I will asdd a try/catch block in there ut I am thinking its another issue with authentication.

**Comment by txsastre** [comment]
Ok. Thanks.
meanwhile I am going to install a new backup apliance from scratch.

**Comment by zipurman** [comment]
I have updated the code. Simple fix as some of your (auto generated) files were still old version.

I would recommend that you delete any files in your /var/www/html/cache/ directory when upgrading. I will code that in asap so that is no longer a user issue.

I would do the following after that, go to the settings page, enter in as much info as possible including user/pass. Then ** go to the engine VM and enter "ovirt-aaa-jdbc-tool user unlock admin" to make sure the admin user hasnt been locked by too many failed api queries. Then click SAVE on the sttings page. Then choose your Domain and Cluster and click SAVE again. Hope that works!

**Comment by zipurman** [comment]
BTW, apache error log will complain sometimes due to the outputs of fdisk queries. I havent been able to silence that as its usually related to dynamic devices and www-data doesnt have access by default. Those errors can be ignored as they dont really create an issue.

**Comment by txsastre** [comment]
still cannot do the "save" option because web stops at "Default restore options" 

but as I told previously I will try a new installation from scratch.

![seleccio_040](https://user-images.githubusercontent.com/10468371/37880290-27999464-3086-11e8-86ef-94c96d758bd6.png)

**Comment by zipurman** [comment]
Try deleting your config.php file

**Comment by txsastre** [comment]
deleted everything and uploaded again.
on ovirt-engine executed` ovirt-aaa-jdbc-tool user unlock admin`

 WebUI is OK, but the settings web still stops at "Default Restore Options"

**Comment by txsastre** [comment]
OK, I've done the BackupEngine VM from scratch, still having the same issue.
Well now I cannot see the button in the oVirt interface, but I go directly to the BackupEngine web, and the same issue appears.

beginning to think that the problem is in the ovirt-engine,  because I am also testing this other project https://github.com/vacosta94/VirtBKP/issues/2#issuecomment-376116254 and also having similar issues

**Comment by zipurman** [comment]
If you can see the save button now, try this.

1. Go to the settings page a fill in all the fields (DONT CLICK SAVE YET)
2. Go to the command line on the engine VM and do a "ovirt-aaa-jdbc-tool user unlock admin"
3. Now click SAVE on the settings page.
4. Hopefully you now see the domains and the Cluster dropdowns with some options in them. If you do, choose the options for those 2 and SAVE again.

If that doesnt work, let me know exactly what you are seeing in the logs for errors.

You could also try this in your browser to see if it helps find the problem, 
goto: 
https://YOUR-IP-OF-ENGINEVM/api/clusters/ 

Then view the source of that page which should have the XML from the API, if not, then your problem is on the Engine.

**Comment by txsastre** [comment]
hi!, thanks for your support.

 I cannot see the SAVE button, so I tested the url of the api 
I think it works because I receive this code

https://192.168.222.200/ovirt-engine/api/clusters

`<clusters><cluster href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88" id="adf5bf56-21f9-11e8-a184-da3173d77f88"><actions><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/resetemulatedmachine" rel="resetemulatedmachine"/></actions><name>Default</name><description>The default server cluster</description><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/affinitygroups" rel="affinitygroups"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/glusterhooks" rel="glusterhooks"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/glustervolumes" rel="glustervolumes"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/enabledfeatures" rel="enabledfeatures"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/externalnetworkproviders" rel="externalnetworkproviders"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/permissions" rel="permissions"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/cpuprofiles" rel="cpuprofiles"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/networkfilters" rel="networkfilters"/><link href="/ovirt-engine/api/clusters/adf5bf56-21f9-11e8-a184-da3173d77f88/networks" rel="networks"/><ballooning_enabled>false</ballooning_enabled><cpu><architecture>x86_64</architecture><type>Intel Nehalem Family</type></cpu><custom_scheduling_policy_properties><property><name>HighUtilization</name><value>80</value></property><property><name>CpuOverCommitDurationMinutes</name><value>2</value></property></custom_scheduling_policy_properties><error_handling><on_error>migrate</on_error></error_handling><fencing_policy><enabled>true</enabled><skip_if_connectivity_broken><enabled>false</enabled><threshold>50</threshold></skip_if_connectivity_broken><skip_if_gluster_bricks_up>false</skip_if_gluster_bricks_up><skip_if_gluster_quorum_not_met>false</skip_if_gluster_quorum_not_met><skip_if_sd_active><enabled>false</enabled></skip_if_sd_active></fencing_policy><firewall_type>firewalld</firewall_type><gluster_service>false</gluster_service><ha_reservation>false</ha_reservation><ksm><enabled>true</enabled><merge_across_nodes>true</merge_across_nodes></ksm><maintenance_reason_required>false</maintenance_reason_required><memory_policy><over_commit><percent>100</percent></over_commit><transparent_hugepages><enabled>true</enabled></transparent_hugepages></memory_policy><migration><auto_converge>inherit</auto_converge><bandwidth><assignment_method>auto</assignment_method></bandwidth><compressed>inherit</compressed><policy id="80554327-0569-496b-bdeb-fcbbf52b827b"/></migration><optional_reason>false</optional_reason><required_rng_sources><required_rng_source>urandom</required_rng_source></required_rng_sources><switch_type>legacy</switch_type><threads_as_cores>false</threads_as_cores><trusted_service>false</trusted_service><tunnel_migration>false</tunnel_migration><version><major>4</major><minor>2</minor></version><virt_service>true</virt_service><data_center href="/ovirt-engine/api/datacenters/adf3b350-21f9-11e8-927a-da3173d77f88" id="adf3b350-21f9-11e8-927a-da3173d77f88"/><mac_pool href="/ovirt-engine/api/macpools/58ca604b-017d-0374-0220-00000000014e" id="58ca604b-017d-0374-0220-00000000014e"/><scheduling_policy href="/ovirt-engine/api/schedulingpolicies/b4ed2332-a7ac-4d5f-9596-99a439cb2812" id="b4ed2332-a7ac-4d5f-9596-99a439cb2812"/></cluster></clusters>`

the tail /var/log/apache2/error.log -f shows
```

[Mon Mar 26 20:21:08.084244 2018] [:error] [pid 995] [client 192.168.222.57:59259] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/functions.php:242\nStack trace:\n#0 /var/www/html/area/backup.php(18): ovirt_rest_api_call('GET', 'vms')\n#1 /var/www/html/site/index.php(6): require('/var/www/html/a...')\n#2 {main}\n  thrown in /var/www/html/functions.php on line 242, referer: https://192.168.222.14/?area=99
[Mon Mar 26 20:21:12.188297 2018] [:error] [pid 996] [client 192.168.222.57:59260] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/functions.php:242\nStack trace:\n#0 /var/www/html/functions.php(428): ovirt_rest_api_call('GET', 'clusters/')\n#1 /var/www/html/area/settings.php(505): sb_clusterlist()\n#2 /var/www/html/site/index.php(6): require('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/functions.php on line 242, referer: https://192.168.222.14/?area=2

```

**Comment by zipurman** [comment]
Are you using Debian or CentOS/RH as your OS for the Backup Appliance VM?

If using CentOS/RH, try this:

yum install php-libxml php-xml php-simplexml

**Comment by txsastre** [comment]
No. I'm using Debian 9
Should I try with CentOS?

**Comment by zipurman** [comment]
No, I also use Debian.

Try:

apt-get install php5.6-xml

/etc/init.d/apache2 restart

**Comment by zipurman** [comment]
If that doesnt work ... I am searching to see what may be missing...

**Comment by zipurman** [comment]
Try:

apt-get install libapache2-mod-php5

**Comment by txsastre** [comment]
I will try tomorrow but I'm Debian 9 is using php7, guess is the same.

**Comment by zipurman** [comment]
I havent tested with php7 yet. This should work:

apt-get install php7.0-xml 
service apache2 restart

**Comment by zipurman** [comment]
Also, make sure you have this installed: 

apt-get install php7.0-curl
service apache2 restart

**Comment by txsastre** [comment]
hi there, with apt-get install php7.0-xml now it works. although I can see all the web plus the "SAVE" button. :D 

Now I'm going to test the setting, if something is wrong I will open another issue.

Thanks !
